### PR TITLE
acceptor: fix input events during connection finalization

### LINKED ISSUE #220: acceptor: sometime assert on expecting X224 but get FastPath
Sometime, mstsc fails to connect to the server:

```
2023-10-16T10:33:33.038633Z DEBUG ironrdp_acceptor: Wait for PDU acceptor.state="ConnectionFinalization" hint=X224Hint
2023-10-16T10:33:33.038638Z TRACE ironrdp_acceptor: PDU received length=40
2023-10-16T10:33:33.038644Z DEBUG ironrdp_acceptor::finalization: Received ShareControlHeader { share_control_pdu: Data(ShareDataHeader { share_data_pdu: Control(ControlPdu { action: Cooperate, grant_id: 0, control_id: 0 }), stream_priority: Low, compression_flags: CompressionFlags(0x0), compression_type: K8 }), pdu_source: 1002, share_id: 0 }
[crates/ironrdp-acceptor/src/finalization.rs:62] &self.state = WaitRequestControl
2023-10-16T10:33:33.038652Z DEBUG ironrdp_acceptor: Wait for PDU acceptor.state="ConnectionFinalization" hint=X224Hint
2023-10-16T10:33:33.038657Z TRACE ironrdp_acceptor: PDU received length=40
2023-10-16T10:33:33.038662Z DEBUG ironrdp_acceptor::finalization: Received ShareControlHeader { share_control_pdu: Data(ShareDataHeader { share_data_pdu: Control(ControlPdu { action: RequestControl, grant_id: 0, control_id: 0 }), stream_priority: Low, compression_flags: CompressionFlags(0x0), compression_type: K8 }), pdu_source: 1002, share_id: 0 }
[crates/ironrdp-acceptor/src/finalization.rs:62] &self.state = WaitFontList
2023-10-16T10:33:33.038670Z DEBUG ironrdp_acceptor: Wait for PDU acceptor.state="ConnectionFinalization" hint=X224Hint
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `FastPath`,
 right: `X224`', crates/ironrdp-pdu/src/lib.rs:338:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:229:5
   4: <ironrdp_pdu::X224Hint as ironrdp_pdu::PduHint>::find_size
             at ./crates/ironrdp-pdu/src/lib.rs:338:17
   5: ironrdp_async::framed::Framed<S>::read_by_hint::{{closure}}
             at ./crates/ironrdp-async/src/framed.rs:164:19
   6: ironrdp_acceptor::single_accept_state::{{closure}}
             at ./crates/ironrdp-acceptor/src/lib.rs:85:14
   7: ironrdp_acceptor::accept_finalize::{{closure}}
             at ./crates/ironrdp-acceptor/src/lib.rs:62:62
   8: ironrdp_server::server::RdpServer::run_connection::{{closure}}
             at ./crates/ironrdp-server/src/server.rs:99:92
   9: ironrdp_server::server::RdpServer::run::{{closure}}
             at ./crates/ironrdp-server/src/server.rs:117:57
  10: server::run::{{closure}}
```
Indeed, there seems to be some input messages before the FontList:
Screenshot from 2023-10-16 14-37-14

### PR DESCRIPTION
**Pull request by mihneabuz**
Fixes #220 

This makes the acceptor accumulate any input events received during connection finalization, so they can be processed before starting the client loop.

Because the FontList is an x224 pdu and input events could be FastPath, I added a new PduHint that matches any pdu.

Also made the acceptor a little more robust and improved logging.

### CODE REVIEW

File: crates/ironrdp-acceptor/src/finalization.rs [hunk 1]
```diff
@@ -223,3 +224,27 @@ fn create_font_map() -> rdp::headers::ShareDataPdu {
...
     })
 }
+
+fn decode_share_control(input: &[u8]) -> ConnectorResult<rdp::headers::ShareControlHeader> {
+    let data_request = pdu::decode::<pdu::mcs::SendDataRequest<'_>>(input).map_err(ConnectorError::pdu)?;
+    let share_control = rdp::headers::ShareControlHeader::from_buffer(Cursor::new(data_request.user_data))?;
+    Ok(share_control)
+}
+
+fn decode_font_list(input: &[u8]) -> Result<rdp::finalization_messages::FontPdu, Vec<u8>> {
```
Comment (CBenoit) [inline crates/ironrdp-acceptor/src/finalization.rs:234]: I would tend to prefer pushing the allocation to the caller, especially given that we don’t have the ownership over `input`:
```suggestion
fn decode_font_list(input: &[u8]) -> Result<rdp::finalization_messages::FontPdu, ()> {
```

```rust
// Callsite
Err(()) => {
    self.input_events.push(input.to_vec());
    (Written::Nothing, FinalizationState::WaitFontList)
}
```

File: crates/ironrdp-acceptor/src/finalization.rs [hunk 2]
```diff
@@ -80,44 +82,42 @@ impl Sequence for FinalizationSequence {
...
+                Ok(font_list) => {
+                    debug!(message = ?font_list, "Received");
 
-                let font_list = rdp::headers::ShareControlHeader::from_buffer(Cursor::new(data.user_data))?;
+                    (Written::Nothing, FinalizationState::SendSynchronizeConfirm)
+                }
 
-                debug!(message = ?font_list, "Received");
+                Err(input_event) => {
+                    self.input_events.push(input_event);
```
Comment (CBenoit) [inline crates/ironrdp-acceptor/src/finalization.rs:116]: May be worth to add a debug or trace log, just in case this could be relevant for debugging something

File: crates/ironrdp-pdu/src/lib.rs [hunk 3]
```diff
@@ -327,6 +327,17 @@ pub trait PduHint: Send + Sync + core::fmt::Debug + 'static {
     fn find_size(&self, bytes: &[u8]) -> PduResult<Option<usize>>;
 }
 
+#[derive(Clone, Copy, Debug)]
+pub struct AnyHint;
```
Comment (CBenoit) [inline crates/ironrdp-pdu/src/lib.rs:331]: I feel "any" is a bit too "wide". Maybe this should be named `RdpPduHint`? X224 and FastPath are not the kind of PDUs we may receive, especially during the CredSSP procedure

File: crates/ironrdp-server/src/server.rs [hunk 4]
```diff
@@ -100,31 +100,41 @@ impl RdpServer {
...
+                    match ironrdp_acceptor::accept_finalize(framed, &mut acceptor).await {
+                        Ok((framed, result)) => self.client_loop(framed, result).await?,
+                        Err(err) => error!(?err, "accept finalize error"),
+                    };
                 }
 
-                Err(e) => {
-                    error!("connection error: {:?}", e);
+                Err(err) => {
+                    error!(?err, "accept begin error");
```
Comment (CBenoit) [inline crates/ironrdp-server/src/server.rs:118]: Nit: FYI, the field is recorded as `error` at other places (although we don’t rely on this fact for anything as of today)

File: crates/ironrdp-server/src/server.rs [hunk 5]
```diff
@@ -100,31 +100,41 @@ impl RdpServer {
...
-    async fn client_loop<S>(&mut self, mut framed: Framed<S>) -> Result<()>
+    async fn client_loop<S>(&mut self, mut framed: Framed<S>, result: AcceptorResult) -> Result<()>
     where
         S: FramedWrite + FramedRead,
     {
         let mut buffer = vec![0u8; 4096];
         let mut encoder = UpdateEncoder::new();
 
+        if !result.input_events.is_empty() {
+            debug!("handling input event backlog from acceptor sequence");
```
Comment (CBenoit) [inline crates/ironrdp-server/src/server.rs:134]: Nit: log messages should be capitalized sentences

File: crates/ironrdp-server/src/server.rs [hunk 6]
```diff
@@ -180,6 +190,25 @@ impl RdpServer {
...
+                Ok(Action::FastPath) => {
+                    let input = FastPathInput::from_buffer(Cursor::new(&frame))?;
+                    self.handle_fastpath(input).await;
+                }
+
+                Ok(Action::X224) => {
+                    let _ = self.handle_x224(&frame).await;
+                }
+
+                _ => unreachable!(),
```
Comment (CBenoit) [inline crates/ironrdp-server/src/server.rs:205]: Are we sure this is really unreachable? My understanding is that we are accumulating the additional frames as-is in the connector, did I miss something?

**Review by CBenoit — COMMENTED** [review]
Thank you a lot!

File: crates/ironrdp-server/src/server.rs (hunk 6 above)
Comment (mihneabuz) [reply crates/ironrdp-server/src/server.rs:205]: If `Action::from_fp_output_header` could return `Err`, that would mean the frame isn't valid, but then it would have already failed in the acceptor loop, because `find_size` would have failed.

File: crates/ironrdp-acceptor/src/connection.rs [hunk 7]
```diff
@@ -51,13 +52,15 @@ impl Acceptor {
...
+                input_events,
             } => Some(AcceptorResult {
-                channels: channels.clone(),
-                capabilities: client_capabilities.clone(),
+                channels: std::mem::take(channels),
+                capabilities: std::mem::take(client_capabilities),
+                input_events: std::mem::take(input_events),
             }),
 
             _ => None,
```
[the remark this answers is not in the document]
Comment (CBenoit) [reply crates/ironrdp-acceptor/src/connection.rs:66]: Oh okay, I see!
An alternative is to set back the original state:
```diff
    pub fn get_result(&mut self) -> Option<AcceptorResult> {
        match std::mem::take(&mut self.state) {
            AcceptorState::Accepted {
                channels,
                client_capabilities,
                input_events,
            } => Some(AcceptorResult {
                channels,
                capabilities: client_capabilities,
                input_events,
            }),
-           _ => None,
+           previous_state => {
+               *self.state = previous_state;
+               None
+           }
        }
    }
```

File: crates/ironrdp-server/src/server.rs (hunk 6 above)
Comment (CBenoit) [reply crates/ironrdp-server/src/server.rs:205]: You’re right! Do you think you could copy put this comment as an inline code comment above the `unreachable!` statement, for future reference?

File: crates/ironrdp-acceptor/src/connection.rs [hunk 8]
```diff
@@ -421,24 +425,36 @@ impl Sequence for Acceptor {
...
-                    Written::Nothing,
-                    AcceptorState::ConnectionFinalization {
-                        channels,
-                        finalization: FinalizationSequence::new(self.user_channel_id, self.io_channel_id),
-                        client_capabilities: confirm.pdu.capability_sets,
-                    },
-                )
+                        (Written::Nothing, AcceptorState::CapabilitiesWaitConfirm { channels })
+                    }
+                }
```
[the remark this answers is not in the document]
Comment (mihneabuz) [reply crates/ironrdp-acceptor/src/connection.rs]: I agree, this looks better. Makes sens to treat this less like an error and more like something that can happen, thanks!

**Review by CBenoit — APPROVED** [review]
LGTM! Since the history is clean, I’ll merge using the "rebase & fast-forward merge" strategy to keep it. There is just a small conflict to resolve, but I can handle that if you prefer

**Comment by mihneabuz** [comment]
Sure you can fix it and merge it. I didn't notice the conflict and already turned off my PC, but I can fix it tomorrow alternatively.

**Comment by CBenoit** [comment]
> Sure you can fix it and merge it. I didn't notice the conflict and already turned off my PC, but I can fix it tomorrow alternatively.

Sounds good. No problem, I handled that, the PR will be merged soon :+1:

**Comment by elmarco** [comment]
thanks!
